/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cc4p1.clientchat;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Albert
 */
public class ClientChatGUI extends javax.swing.JFrame {

    /**
     * Creates new form ClientChatGUI
     */
    public ClientChatGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        ScreenTA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        MessagesTA = new javax.swing.JTextArea();
        SendBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ResponseTA = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat Cliente");

        ScreenTA.setEditable(false);
        ScreenTA.setColumns(20);
        ScreenTA.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        ScreenTA.setRows(5);
        jScrollPane1.setViewportView(ScreenTA);

        MessagesTA.setColumns(20);
        MessagesTA.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        MessagesTA.setLineWrap(true);
        MessagesTA.setRows(5);
        jScrollPane2.setViewportView(MessagesTA);

        SendBtn.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        SendBtn.setText("Send");
        SendBtn.setFocusPainted(false);
        SendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendBtnActionPerformed(evt);
            }
        });

        ResponseTA.setEditable(false);
        ResponseTA.setColumns(20);
        ResponseTA.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        ResponseTA.setRows(5);
        jScrollPane3.setViewportView(ResponseTA);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jTable2.setEnabled(false);
        jScrollPane5.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(SendBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendBtnActionPerformed
        String clientMessage = MessagesTA.getText().trim();
        
        // Los mensajes enviados por chat se manejan por palabras clave para simular una IA jejeje:
        // "saldo" + "id" -> consulta los datos de cuenta especificada
        // "transacciones" + "id" -> consulta las transacciones de la cuenta especificada
        // "prestamos" + "id" -> consulta los prestamos de la cuenta especificada
        
        if(!clientMessage.isEmpty()){
            
            ScreenTA.append("Tú: " + clientMessage + "\n");
            MessagesTA.setText("");
            
            try{
                
                String response = MessageProcessor(clientMessage);                
                ResponseTA.append("Respuesta: " + response + "\n");
                
            }catch(Exception ex){
                ResponseTA.append("Error: " + ex.getMessage() + "\n\n");
            }
        }else{
            ResponseTA.append("No se pudo procesar el mensaje");
        }
    }//GEN-LAST:event_SendBtnActionPerformed
    
    public String MessageProcessor(String message) throws Exception{
        Pattern pattern = Pattern.compile("(\\d+)");
        Matcher matcher = pattern.matcher(message);
                
        if (!matcher.find()) {
            ScreenTA.append("Chat banco: El formato de mensajes es incorrecto");        
            return "No se pudo procesar el mensaje";
        }
        
        String idAccount = matcher.group(1);
        
        message = message.toLowerCase();
        
        String response = "";
        
        if (message.contains("saldo")) {
            ScreenTA.append("Chat banco: Imprimiendo saldo de la cuenta " + idAccount + "\n");
            response = HttpHandler.sendGet("http://localhost:8080/consultar_cuenta?id=" + idAccount);
            response = JsonResponseProcessor(response, "saldo");
            response = "El saldo de la cuenta " + idAccount + " es " + response;
            
        } else if (message.contains("transaccion") || message.contains("transacciones")) {
            ScreenTA.append("Chat banco: Imprimiendo transacciones de la cuenta " + idAccount + "\n");
            response = HttpHandler.sendGet("http://localhost:8080/consultar_transacciones?id=" + idAccount);
            
        } else if (message.contains("prestamo") || message.contains("préstamo") || message.contains("prestamos")) {
            ScreenTA.append("Chat banco: Imprimiendo lista de préstamos de la cuenta " + idAccount + "\n");
            response = HttpHandler.sendGet("http://localhost:8080/consultar_prestamos?id=" + idAccount);
            
        } else {
            ScreenTA.append("Chat banco: No reconozco la solicitud. Prueba con palabras como 'saldo', 'transacciones' o 'préstamos'.\n");            
            response = "No se pudo realizar la consulta";
        }
        
        return response;
    }
    
    public String JsonResponseProcessor(String jsonText, String type){
        String response = "";
        
        switch(type){
            case "saldo":
                // Extraemos el valor del "saldo"
                int saldoIndex = jsonText.indexOf("\"saldo\":");
                int endIndex = jsonText.indexOf("}", saldoIndex);
                String saldo = jsonText.substring(saldoIndex + 9, endIndex - 1).replace("\"", "").trim();
                response = saldo;
                break;
            case "transaccion":
                break;
            case "prestamo":
                break;
            default:
                break;
        }
        
        return response;
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea MessagesTA;
    private javax.swing.JTextArea ResponseTA;
    private javax.swing.JTextArea ScreenTA;
    private javax.swing.JButton SendBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
