cuentas.p0 = nodeA,nodeB,nodeC
cuentas.p1 = nodeB,nodeC,nodeA
cuentas.p2 = nodeC,nodeA,nodeB

transacciones.p0 = nodeA,nodeB,nodeC
transacciones.p1 = nodeB,nodeC,nodeA
transacciones.p2 = nodeC,nodeA,nodeB

prestamos.p0 = nodeA,nodeB,nodeC
prestamos.p1 = nodeB,nodeC,nodeA
prestamos.p2 = nodeC,nodeA,nodeB

pagos.p0 = nodeA,nodeB,nodeC
pagos.p1 = nodeB,nodeC,nodeA
pagos.p2 = nodeC,nodeA,nodeB
